import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Drink from "../components/drink"
import Navbar from '../components/navbar'

export default function Home() {
  const [state, setState] = useState([])
    useEffect (() => {
        fetch('https://www.thecocktaildb.com/api/json/v1/1/search.php?f=a')
        .then(response => response.json())
        .then(result => {
            console.log(result.drinks)
            setState(result.drinks)
        })

    }, []);
  return (
    <div className=''>
      <Head>
        <title>Cocktailspedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='bootstrap/dist/css/bootstrap.min.css' />
      </Head>
      <Navbar />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Cocktails Pedia
        </h1>

        <Drink dataDrink={state} />
      </main> 

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
