import Head from 'next/head'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import Drink from "../components/drink"
import { SearchOutlined } from '@ant-design/icons'
import { Input } from 'antd'

export default function Home() {
  const [state, setState] = useState([])
  const [search, setSearch] = useState({
    searchInput:[]
  })
    
  useEffect (() => {
        fetch('https://www.thecocktaildb.com/api/json/v1/1/search.php?f=a')
        .then(response => response.json())
        .then(result => {
            setState(result.drinks)
        })
  }, []);

  const handleChange = (e) => {
    const change = e.target.value;
      if(change) {
        fetch(`https://www.thecocktaildb.com/api/json/v1/1/search.php?s=${change}`)
        .then(response => response.json())
        .then(result => {
            setSearch({searchInput: change})
            setState(result.drinks)
        })
      } else {
        fetch('https://www.thecocktaildb.com/api/json/v1/1/search.php?f=a')
        .then(response => response.json())
        .then(result => {
            setState(result.drinks)
        })
      }
  }

  if(!search) {
    return <div className='text-center'>
      <h3 className='fw-bold'> Data Not Found</h3>
    </div>
  }

  return (
    <>
      <Head>
        <title>Cocktailspedia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="background-banner position-relative">
        <h1 className='position-absolute bottom-0 start-50 translate-middle fw-bold' style={{ color: '#fff' }}>
          Cocktails Pedia
        </h1>
        <div className="position-absolute top-100 start-50 translate-middle shadow d-flex align-items-center rounded-3" style={{ width: '70%', backgroundColor: '#fff' }}>
          <Input className='rounded-3' prefix={<SearchOutlined className="site-form-item-icon mr-3" />}
            placeholder="Search"
            allowClear
            onChange={handleChange}
            style={{ height: '50px' }} />
        </div>
      </div>

      <main className={styles.main}>
        <Drink dataDrink={state} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  )
}
